### ISSUE TITLE
Does not allow Carrierwave 1.1.0

### ISSUE THREAD

**Issue by zealot128** [nifuramu/carrierwave-imageoptim#8]
The cw-imageoptim does not allow the most recent version of carrierwave (which is recommended for Rails 5.1 for example).
There are already forks out that removed the version constraint, e.g.:

https://github.com/djohnson/carrierwave-imageoptim/commit/0f3463cd0ad1baeaa8134cc4c37811d72234e1c7

**Comment by nifuramu** [comment]
thanks info!
